apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
images:
- name: image_name
  newName: 493742262720.dkr.ecr.us-east-2.amazonaws.com/qa-fastapi-app
  newTag: latest
