name: CI/CD Pipeline for EKS Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
    DEPLOYMENT_NAME: qa-fastapi-app-deploy
    IMAGE: qa-fastapi-app
